Feature5 send accrual
50-003-ESC-Gang/Loyalty-Points pull request #90
Opened 2022-07-20 12:50 UTC by lingaoliu105

For demonstrating feature 5: can adjust the auto sending and retrieving time sooner, demonstrate the program and show drivehq content

2022-07-20 13:18 UTC, ExtremelySunnyYK commented on app/jobs/send_accrual_job.rb
> +  config.active_job.queue_adapter = :sidekiq
error here

2022-07-20 13:19 UTC, ExtremelySunnyYK commented on app/jobs/send_accrual_job.rb
> +    system "cmdftp -s:drivehq_send.txt -%filepath:#{args[0]}"
what does this line do?

2022-07-20 13:20 UTC, ExtremelySunnyYK commented on app/jobs/send_accrual_job.rb
> +    system "cmdftp -s:drivehq_send.txt -%filepath:#{args[0]}"
it to send to send to sftp, we need to do this

2022-07-20 13:23 UTC, ExtremelySunnyYK commented on app/jobs/send_accrual_job.rb
> +    system "cmdftp -s:drivehq_send.txt -%filepath:#{args[0]}"
how do we know if this work?

2022-07-20 14:27 UTC, ExtremelySunnyYK commented on app/controllers/loyalty_program_data_controller.rb
> +        @transaction = Transaction.create(amount: loyalty_program_datum_params[:points].to_d, loyalty_program_data_id: params[:id], status: 0, account_id: current_user.id)
so is this loyalty_program_data_id? or?

2022-07-20 14:27 UTC, ExtremelySunnyYK commented on app/controllers/loyalty_program_data_controller.rb
> +        @transaction = Transaction.create(amount: loyalty_program_datum_params[:points].to_d, loyalty_program_data_id: params[:id], status: 0, account_id: current_user.id)
loyalty_program_datum_id

2022-07-21 10:13 UTC, mattChrisP commented on app/models/transaction.rb
> +  belongs_to :loyalty_program_datum
I think should be ok

2022-07-21 12:39 UTC, ExtremelySunnyYK commented
![image](https://user-images.githubusercontent.com/46377366/180215314-87fb0a73-674f-4cdc-b1e9-38f30f1dd4a9.png)
Error over here

2022-07-21 13:09 UTC, ExtremelySunnyYK requested changes
fix errors and try on your local machine. Thanks

2022-07-22 00:37 UTC, merged